version: '2'

services:
  php:
    image: php:7.2-fpm
    volumes:
      - .:/var/www/symfony

  nginx:
    image: nginx:latest
    volumes_from:
      - php
    volumes:
      - ./docker/symfony.conf:/etc/nginx/conf.d/default.conf
    environment:
      VIRTUAL_HOST: crypto-investor.efavre.online
      LETSENCRYPT_HOST: crypto-investor.efavre.online
      LETSENCRYPT_EMAIL: swisscatman@gmail.com

networks:
  default:
    external:
      name: nginx-proxy