version: '3'

services:
  php:
    image: php:7.2-fpm
    volumes:
      - .:/var/www/symfony

  nginx:
    image: nginx:latest
    volumes:
      - ./docker/symfony.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/symfony
    environment:
      VIRTUAL_HOST: ${APP_HOST:-crypto-investor.efavre.online}
      LETSENCRYPT_HOST: ${APP_HOST:-crypto-investor.efavre.online}
      LETSENCRYPT_EMAIL: swisscatman@gmail.com

networks:
  default:
    external:
      name: nginx-proxy